name: Build and Release Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: platformio run

      - name: Copy firmware to Release folder
        run: |
          mkdir -p Release
          find .pio/build -name "firmware.bin" -exec cp {} Release/ \;

      - name: Copy firmware.json to Release folder
        run: cp Release/firmware.json Release/

      - name: Create GitHub Release and Upload Firmware
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Firmware v${{ github.run_number }}
          files: |
            Release/firmware.bin
            Release/firmware.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
